//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaderTable
    {
        public int Id { get; set; }
        public string NickName { get; set; }
        public string vsBotOrPlayer { get; set; }
        public string Points { get; set; }
    }
}
